from __future__ import annotations

from ..utils.paths import repo_root
from ..utils.subproc import RunResult, python_exe, run

_GUI_PURE_MYPY_TARGETS = (
    "keyrgb/gui/__init__.py",
    "keyrgb/gui/calibrator/__init__.py",
    "keyrgb/gui/calibrator/__main__.py",
    "keyrgb/gui/calibrator/_app_bootstrap.py",
    "keyrgb/gui/calibrator/_app_logic.py",
    "keyrgb/gui/calibrator/_internal/__init__.py",
    "keyrgb/gui/calibrator/_internal/_app_canvas_interactions.py",
    "keyrgb/gui/calibrator/_internal/_app_profile_layout.py",
    "keyrgb/gui/calibrator/_internal/_app_profile_layout_bindings.py",
    "keyrgb/gui/calibrator/_internal/_app_runtime_deps.py",
    "keyrgb/gui/calibrator/app.py",
    "keyrgb/gui/calibrator/helpers/__init__.py",
    "keyrgb/gui/calibrator/helpers/canvas_render.py",
    "keyrgb/gui/calibrator/helpers/geometry.py",
    "keyrgb/gui/calibrator/helpers/keyboard_preview.py",
    "keyrgb/gui/calibrator/helpers/probe.py",
    "keyrgb/gui/calibrator/helpers/profile_storage.py",
    "keyrgb/gui/calibrator/launch.py",
    "keyrgb/gui/perkey/__init__.py",
    "keyrgb/gui/perkey/__main__.py",
    "keyrgb/gui/perkey/canvas.py",
    "keyrgb/gui/perkey/canvas_impl/__init__.py",
    "keyrgb/gui/perkey/canvas_impl/_canvas_drawing.py",
    "keyrgb/gui/perkey/canvas_impl/_canvas_drawing_helpers.py",
    "keyrgb/gui/perkey/canvas_impl/_canvas_drawing_render.py",
    "keyrgb/gui/perkey/canvas_impl/_canvas_drawing_runtime.py",
    "keyrgb/gui/perkey/canvas_impl/_canvas_events.py",
    "keyrgb/gui/perkey/canvas_impl/_canvas_identity.py",
    "keyrgb/gui/perkey/canvas_impl/_canvas_services.py",
    "keyrgb/gui/perkey/canvas_impl/canvas_hit_testing.py",
    "keyrgb/gui/perkey/color_utils.py",
    "keyrgb/gui/perkey/commit_pipeline.py",
    "keyrgb/gui/perkey/editor.py",
    "keyrgb/gui/perkey/editor_support/__init__.py",
    "keyrgb/gui/perkey/editor_support/actions.py",
    "keyrgb/gui/perkey/editor_support/backdrop.py",
    "keyrgb/gui/perkey/editor_support/bootstrap.py",
    "keyrgb/gui/perkey/editor_support/dirty_state.py",
    "keyrgb/gui/perkey/editor_support/layout.py",
    "keyrgb/gui/perkey/editor_support/layout_state.py",
    "keyrgb/gui/perkey/editor_support/runtime.py",
    "keyrgb/gui/perkey/editor_support/selection.py",
    "keyrgb/gui/perkey/editor_support/ui.py",
    "keyrgb/gui/perkey/hardware.py",
    "keyrgb/gui/perkey/keyboard_apply.py",
    "keyrgb/gui/perkey/launch.py",
    "keyrgb/gui/perkey/lightbar_controls.py",
    "keyrgb/gui/perkey/lightbar_layout.py",
    "keyrgb/gui/perkey/ops/__init__.py",
    "keyrgb/gui/perkey/ops/color_apply_ops.py",
    "keyrgb/gui/perkey/ops/color_map_ops.py",
    "keyrgb/gui/perkey/overlay/__init__.py",
    "keyrgb/gui/perkey/overlay/autosync.py",
    "keyrgb/gui/perkey/overlay/controls.py",
    "keyrgb/gui/perkey/overlay/drag.py",
    "keyrgb/gui/perkey/profile_management.py",
    "keyrgb/gui/perkey/secondary_lighting.py",
    "keyrgb/gui/perkey/ui/__init__.py",
    "keyrgb/gui/perkey/ui/_profile_actions_support.py",
    "keyrgb/gui/perkey/ui/_profile_actions_ui.py",
    "keyrgb/gui/perkey/ui/_sample_tool_support.py",
    "keyrgb/gui/perkey/ui/backdrop.py",
    "keyrgb/gui/perkey/ui/bulk_color.py",
    "keyrgb/gui/perkey/ui/calibrator.py",
    "keyrgb/gui/perkey/ui/full_map.py",
    "keyrgb/gui/perkey/ui/keymap.py",
    "keyrgb/gui/perkey/ui/layout_setup.py",
    "keyrgb/gui/perkey/ui/layout_slots.py",
    "keyrgb/gui/perkey/ui/lighting_areas.py",
    "keyrgb/gui/perkey/ui/profile_actions.py",
    "keyrgb/gui/perkey/ui/sample_tool.py",
    "keyrgb/gui/perkey/ui/selection.py",
    "keyrgb/gui/perkey/ui/status.py",
    "keyrgb/gui/perkey/ui/wheel_apply.py",
    "keyrgb/gui/perkey/window_geometry.py",
    "keyrgb/gui/reference/__init__.py",
    "keyrgb/gui/reference/overlay_geometry.py",
    "keyrgb/gui/settings/__init__.py",
    "keyrgb/gui/settings/__main__.py",
    "keyrgb/gui/settings/_settings_reader.py",
    "keyrgb/gui/settings/_settings_scheduler.py",
    "keyrgb/gui/settings/_settings_values.py",
    "keyrgb/gui/settings/_settings_window_constants.py",
    "keyrgb/gui/settings/diagnostics_runner.py",
    "keyrgb/gui/settings/hardware_hint.py",
    "keyrgb/gui/settings/os_autostart.py",
    "keyrgb/gui/settings/panels/__init__.py",
    "keyrgb/gui/settings/panels/_wrap_sync.py",
    "keyrgb/gui/settings/panels/autostart_panel.py",
    "keyrgb/gui/settings/panels/bottom_bar_panel.py",
    "keyrgb/gui/settings/panels/dim_sync_panel.py",
    "keyrgb/gui/settings/panels/experimental_backends_panel.py",
    "keyrgb/gui/settings/panels/power_management_panel.py",
    "keyrgb/gui/settings/panels/power_source_panel.py",
    "keyrgb/gui/settings/panels/time_scheduler_panel.py",
    "keyrgb/gui/settings/panels/version_panel.py",
    "keyrgb/gui/settings/scrollable_area.py",
    "keyrgb/gui/settings/settings_state.py",
    "keyrgb/gui/settings/window.py",
    "keyrgb/gui/theme/__init__.py",
    "keyrgb/gui/theme/detect.py",
    "keyrgb/gui/theme/ttk.py",
    "keyrgb/gui/utils/__init__.py",
    "keyrgb/gui/utils/backdrop_image_cache.py",
    "keyrgb/gui/utils/deck_render_cache.py",
    "keyrgb/gui/utils/key_draw_style.py",
    "keyrgb/gui/utils/profile_backdrop_storage.py",
    "keyrgb/gui/utils/tk_async.py",
    "keyrgb/gui/utils/window_centering.py",
    "keyrgb/gui/utils/window_geometry.py",
    "keyrgb/gui/utils/window_icon.py",
    "keyrgb/gui/widgets/__init__.py",
    "keyrgb/gui/widgets/color_wheel/__init__.py",
    "keyrgb/gui/widgets/color_wheel/_color_wheel_runtime.py",
    "keyrgb/gui/widgets/color_wheel/_color_wheel_ui.py",
    "keyrgb/gui/widgets/color_wheel/color_wheel.py",
    "keyrgb/gui/widgets/color_wheel/color_wheel_image.py",
    "keyrgb/gui/widgets/color_wheel/demo.py",
    "keyrgb/gui/widgets/color_wheel/utils.py",
    "keyrgb/gui/widgets/dropdown.py",
    "keyrgb/gui/windows/__init__.py",
    "keyrgb/gui/windows/_reactive_color_bootstrap.py",
    "keyrgb/gui/windows/_reactive_color_geometry.py",
    "keyrgb/gui/windows/_reactive_color_init_adapter.py",
    "keyrgb/gui/windows/_reactive_color_interactions.py",
    "keyrgb/gui/windows/_reactive_color_runtime.py",
    "keyrgb/gui/windows/_reactive_color_settings_adapter.py",
    "keyrgb/gui/windows/_reactive_color_state.py",
    "keyrgb/gui/windows/_reactive_color_ui.py",
    "keyrgb/gui/windows/_reactive_color_wiring.py",
    "keyrgb/gui/windows/_support/__init__.py",
    "keyrgb/gui/windows/_support/_support_window_actions.py",
    "keyrgb/gui/windows/_support/_support_window_backend_probe.py",
    "keyrgb/gui/windows/_support/_support_window_backend_probe_adapter.py",
    "keyrgb/gui/windows/_support/_support_window_backend_probe_config.py",
    "keyrgb/gui/windows/_support/_support_window_exports.py",
    "keyrgb/gui/windows/_support/_support_window_geometry.py",
    "keyrgb/gui/windows/_support/_support_window_job_wiring.py",
    "keyrgb/gui/windows/_support/_support_window_jobs.py",
    "keyrgb/gui/windows/_support/_support_window_probe_dialog_layout.py",
    "keyrgb/gui/windows/_support/_support_window_probe_dialogs.py",
    "keyrgb/gui/windows/_support/_support_window_runtime_services.py",
    "keyrgb/gui/windows/_support/_support_window_session_bridge.py",
    "keyrgb/gui/windows/_support/_support_window_state.py",
    "keyrgb/gui/windows/_support/_support_window_tasks.py",
    "keyrgb/gui/windows/_support/_support_window_text_io.py",
    "keyrgb/gui/windows/_support/_support_window_ui.py",
    "keyrgb/gui/windows/_support/_support_window_ui_sections.py",
    "keyrgb/gui/windows/_support/_support_window_ui_shared.py",
    "keyrgb/gui/windows/_support_window_runtime_deps.py",
    "keyrgb/gui/windows/_uniform_color_bootstrap.py",
    "keyrgb/gui/windows/_uniform_color_interactions.py",
    "keyrgb/gui/windows/_uniform_color_state.py",
    "keyrgb/gui/windows/_uniform_color_ui.py",
    "keyrgb/gui/windows/_uniform_init_adapter.py",
    "keyrgb/gui/windows/power_mode.py",
    "keyrgb/gui/windows/reactive_color.py",
    "keyrgb/gui/windows/support.py",
    "keyrgb/gui/windows/uniform.py",
)


def _combine_mypy_results(primary: RunResult, gui_pure: RunResult) -> RunResult:
    return RunResult(
        command_str=f"{primary.command_str} && {gui_pure.command_str}",
        stdout=primary.stdout + gui_pure.stdout,
        stderr=primary.stderr + gui_pure.stderr,
        exit_code=primary.exit_code or gui_pure.exit_code,
    )


def mypy_runner() -> RunResult:
    root = repo_root()

    # Use pyproject.toml configuration if present.
    # Keep the established runtime scope, then check the opted-in GUI module
    # set without following imports into Tk-heavy surfaces that are not yet
    # annotated. This tuple is a ratchet: modules may be added as they pass
    # mypy in the combined run, but never removed (campaign C2).
    primary = run(
        [
            python_exe(),
            "-m",
            "mypy",
            "keyrgb/core",
            "keyrgb/tray",
            "buildpython",
            "scripts/release",
            "tests/buildpython",
        ],
        cwd=str(root),
        env_overrides={"KEYRGB_HW_TESTS": "0"},
    )
    gui_pure = run(
        [
            python_exe(),
            "-m",
            "mypy",
            "--follow-imports=skip",
            *_GUI_PURE_MYPY_TARGETS,
        ],
        cwd=str(root),
        env_overrides={"KEYRGB_HW_TESTS": "0"},
    )
    return _combine_mypy_results(primary, gui_pure)
