from __future__ import annotations

SPECIAL_KEY_NAMES: dict[str, str] = {
    "ESC": "esc",
    "GRAVE": "grave",
    "MINUS": "minus",
    "EQUAL": "equal",
    "BACKSPACE": "backspace",
    "TAB": "tab",
    "CAPSLOCK": "caps",
    "ENTER": "enter",
    "SPACE": "space",
    "LEFTSHIFT": "lshift",
    "RIGHTSHIFT": "rshift",
    "LEFTCTRL": "lctrl",
    "RIGHTCTRL": "rctrl",
    "LEFTALT": "lalt",
    "RIGHTALT": "ralt",
    "LEFTMETA": "lwin",
    "RIGHTMETA": "rwin",
    "COMPOSE": "menu",
    "MENU": "menu",
    "BACKSLASH": "bslash",
    "102ND": "nonusbackslash",
    "LEFTBRACE": "lbracket",
    "RIGHTBRACE": "rbracket",
    "SEMICOLON": "semicolon",
    "APOSTROPHE": "quote",
    "COMMA": "comma",
    "DOT": "dot",
    "SLASH": "slash",
    "DELETE": "del",
    "INSERT": "ins",
    "HOME": "home",
    "END": "end",
    "PAGEUP": "pgup",
    "PAGEDOWN": "pgdn",
    "UP": "up",
    "DOWN": "down",
    "LEFT": "left",
    "RIGHT": "right",
    "NUMLOCK": "numlock",
    "KPSLASH": "numslash",
    "KPASTERISK": "numstar",
    "KPMINUS": "numminus",
    "KPPLUS": "numplus",
    "KPENTER": "numenter",
    "KPDOT": "numdot",
    "SYSRQ": "prtsc",
    "PRINT": "prtsc",
    "SCROLLLOCK": "sc",
    "PAUSE": "pause",
    "BREAK": "pause",
    "VOLUMEUP": "volup",
    "VOLUMEDOWN": "voldown",
    "MUTE": "mute",
    "PLAYPAUSE": "play",
    "PLAY": "play",
    "STOP": "stop",
    "NEXTSONG": "next",
    "PREVIOUSSONG": "prev",
    "CALC": "calc",
    "MAIL": "mail",
    "WWW": "www",
    "HOMEPAGE": "home",
    "BACK": "back",
    "FORWARD": "forward",
}


def keyboard_letter_keys(evdev: object) -> set[int]:
    ecodes = getattr(evdev, "ecodes")
    return {
        ecodes.KEY_A,
        ecodes.KEY_B,
        ecodes.KEY_C,
        ecodes.KEY_D,
        ecodes.KEY_E,
        ecodes.KEY_F,
        ecodes.KEY_G,
        ecodes.KEY_H,
        ecodes.KEY_I,
        ecodes.KEY_J,
        ecodes.KEY_K,
        ecodes.KEY_L,
        ecodes.KEY_M,
        ecodes.KEY_N,
        ecodes.KEY_O,
        ecodes.KEY_P,
        ecodes.KEY_Q,
        ecodes.KEY_R,
        ecodes.KEY_S,
        ecodes.KEY_T,
        ecodes.KEY_U,
        ecodes.KEY_V,
        ecodes.KEY_W,
        ecodes.KEY_X,
        ecodes.KEY_Y,
        ecodes.KEY_Z,
    }


def keyboard_control_keys(evdev: object) -> set[int]:
    ecodes = getattr(evdev, "ecodes")
    return {
        ecodes.KEY_SPACE,
        ecodes.KEY_ENTER,
        ecodes.KEY_TAB,
        ecodes.KEY_BACKSPACE,
        ecodes.KEY_LEFTSHIFT,
        ecodes.KEY_RIGHTSHIFT,
    }
